In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(arr1.shape)

(5,)


In [10]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(5,1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
arr2=np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)


In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr1-np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [22]:
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [23]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0][0])
arr[1:,2:]
arr[0:2]


1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr[0:2,1:]
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
arr[0][0]=100
print(arr)
arr[1:]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [34]:
data=np.array([1,2,3,4,5,6])
print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.std(data))

3.5
3.5
2.9166666666666665
1.707825127659933


In [36]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
n_data=(data-mean)/std_dev
print(n_data)
print(np.mean(n_data))
print(np.std(n_data))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


In [40]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5
print(data[data>5])
print(data)

[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])